---
galaxy_info:
  author: Ansible VPS Automation
  description: Deploy Terraform Code into the VPS
  min_ansible_version: 2.18
  platforms:
    - name: Debian
      versions:
        - bullseye
        - bookworm
        - trixie
  galaxy_tags:
    - minikube
    - kubernetes
    - terraform
    - deployment
    - infrastructure

dependencies: []