---
galaxy_info:
  author: Ansible VPS Automation
  description: Inject SSH public key for secure access
  min_ansible_version: 2.18
  platforms:
    - name: Debian
      versions:
        - bullseye
        - bookworm
        - trixie
  galaxy_tags:
    - ssh
    - security
    - authentication

dependencies: []
