apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-pvc-restore
  namespace: ${monitoring_namespace}
spec:
  storageClassName: csi-hostpath-sc
  dataSource:
    name: prometheus-snapshot
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi