---
galaxy_info:
  author: Ansible VPS Automation
  description: Kubernetes preparation (crictl, CNI plugins, cri-dockerd)
  min_ansible_version: 2.18
  platforms:
    - name: Debian
      versions:
        - bullseye
        - bookworm
        - trixie
  galaxy_tags:
    - kubernetes
    - k8s
    - crictl
    - cri-dockerd
    - cni
    - container-runtime

dependencies: []
