apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Values.appName }}-metrics
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.appName }}
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
  namespaceSelector:
    matchNames:
    - {{ .Values.namespace }}