---
galaxy_info:
  author: Ansible VPS Automation
  description: Docker installation and configuration with IPv4/IPv6 support
  min_ansible_version: 2.18
  platforms:
    - name: Debian
      versions:
        - bullseye
        - bookworm
        - trixie
  galaxy_tags:
    - docker
    - containers
    - networking
    - ipv6
    - firewall

dependencies: []
